// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="vadd_vadd,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.866910,HLS_SYN_LAT=4243,HLS_SYN_TPT=4173,HLS_SYN_MEM=6,HLS_SYN_DSP=0,HLS_SYN_FF=3332,HLS_SYN_LUT=4449,HLS_VERSION=2024_1}" *)

module vadd (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        event_done,
        interrupt,
        event_start,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        stall_start_ext,
        stall_done_ext,
        stall_start_str,
        stall_done_str,
        stall_start_int,
        stall_done_int
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   event_done;
output   interrupt;
output   event_start;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   stall_start_ext;
output   stall_done_ext;
output   stall_start_str;
output   stall_done_str;
output   stall_start_int;
output   stall_done_int;

reg stall_start_ext;
reg stall_done_ext;
reg stall_start_str;
reg stall_done_str;
reg stall_start_int;
reg stall_done_int;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] in1;
wire   [63:0] in2;
wire   [63:0] out_r;
wire   [31:0] size;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [31:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [8:0] gmem0_RFIFONUM;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [31:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [8:0] gmem1_RFIFONUM;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_out_r_c_din;
wire    entry_proc_U0_out_r_c_write;
wire    entry_proc_U0_ap_ext_blocking_n;
wire    entry_proc_U0_ap_str_blocking_n;
wire    entry_proc_U0_ap_int_blocking_n;
wire    read_input_U0_ap_start;
wire    read_input_U0_ap_done;
wire    read_input_U0_ap_continue;
wire    read_input_U0_ap_idle;
wire    read_input_U0_ap_ready;
wire    read_input_U0_start_out;
wire    read_input_U0_start_write;
wire    read_input_U0_m_axi_gmem0_AWVALID;
wire   [63:0] read_input_U0_m_axi_gmem0_AWADDR;
wire   [0:0] read_input_U0_m_axi_gmem0_AWID;
wire   [31:0] read_input_U0_m_axi_gmem0_AWLEN;
wire   [2:0] read_input_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] read_input_U0_m_axi_gmem0_AWBURST;
wire   [1:0] read_input_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] read_input_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] read_input_U0_m_axi_gmem0_AWPROT;
wire   [3:0] read_input_U0_m_axi_gmem0_AWQOS;
wire   [3:0] read_input_U0_m_axi_gmem0_AWREGION;
wire   [0:0] read_input_U0_m_axi_gmem0_AWUSER;
wire    read_input_U0_m_axi_gmem0_WVALID;
wire   [31:0] read_input_U0_m_axi_gmem0_WDATA;
wire   [3:0] read_input_U0_m_axi_gmem0_WSTRB;
wire    read_input_U0_m_axi_gmem0_WLAST;
wire   [0:0] read_input_U0_m_axi_gmem0_WID;
wire   [0:0] read_input_U0_m_axi_gmem0_WUSER;
wire    read_input_U0_m_axi_gmem0_ARVALID;
wire   [63:0] read_input_U0_m_axi_gmem0_ARADDR;
wire   [0:0] read_input_U0_m_axi_gmem0_ARID;
wire   [31:0] read_input_U0_m_axi_gmem0_ARLEN;
wire   [2:0] read_input_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] read_input_U0_m_axi_gmem0_ARBURST;
wire   [1:0] read_input_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] read_input_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] read_input_U0_m_axi_gmem0_ARPROT;
wire   [3:0] read_input_U0_m_axi_gmem0_ARQOS;
wire   [3:0] read_input_U0_m_axi_gmem0_ARREGION;
wire   [0:0] read_input_U0_m_axi_gmem0_ARUSER;
wire    read_input_U0_m_axi_gmem0_RREADY;
wire    read_input_U0_m_axi_gmem0_BREADY;
wire   [31:0] read_input_U0_size_c1_din;
wire    read_input_U0_size_c1_write;
wire   [31:0] read_input_U0_inStream1_din;
wire    read_input_U0_inStream1_write;
wire    read_input_U0_ap_ext_blocking_n;
wire    read_input_U0_ap_str_blocking_n;
wire    read_input_U0_ap_int_blocking_n;
wire    read_input_1_U0_ap_start;
wire    read_input_1_U0_ap_done;
wire    read_input_1_U0_ap_continue;
wire    read_input_1_U0_ap_idle;
wire    read_input_1_U0_ap_ready;
wire    read_input_1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] read_input_1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] read_input_1_U0_m_axi_gmem1_AWID;
wire   [31:0] read_input_1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] read_input_1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] read_input_1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] read_input_1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] read_input_1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] read_input_1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] read_input_1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] read_input_1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] read_input_1_U0_m_axi_gmem1_AWUSER;
wire    read_input_1_U0_m_axi_gmem1_WVALID;
wire   [31:0] read_input_1_U0_m_axi_gmem1_WDATA;
wire   [3:0] read_input_1_U0_m_axi_gmem1_WSTRB;
wire    read_input_1_U0_m_axi_gmem1_WLAST;
wire   [0:0] read_input_1_U0_m_axi_gmem1_WID;
wire   [0:0] read_input_1_U0_m_axi_gmem1_WUSER;
wire    read_input_1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] read_input_1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] read_input_1_U0_m_axi_gmem1_ARID;
wire   [31:0] read_input_1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] read_input_1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] read_input_1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] read_input_1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] read_input_1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] read_input_1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] read_input_1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] read_input_1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] read_input_1_U0_m_axi_gmem1_ARUSER;
wire    read_input_1_U0_m_axi_gmem1_RREADY;
wire    read_input_1_U0_m_axi_gmem1_BREADY;
wire   [31:0] read_input_1_U0_inStream2_din;
wire    read_input_1_U0_inStream2_write;
wire    read_input_1_U0_ap_ext_blocking_n;
wire    read_input_1_U0_ap_str_blocking_n;
wire    read_input_1_U0_ap_int_blocking_n;
wire    compute_add_U0_ap_start;
wire    compute_add_U0_ap_done;
wire    compute_add_U0_ap_continue;
wire    compute_add_U0_ap_idle;
wire    compute_add_U0_ap_ready;
wire    compute_add_U0_size_read;
wire   [31:0] compute_add_U0_size_c_din;
wire    compute_add_U0_size_c_write;
wire    compute_add_U0_inStream1_read;
wire    compute_add_U0_inStream2_read;
wire   [31:0] compute_add_U0_outStream_din;
wire    compute_add_U0_outStream_write;
wire    compute_add_U0_ap_ext_blocking_n;
wire    compute_add_U0_ap_str_blocking_n;
wire    compute_add_U0_ap_int_blocking_n;
wire    write_result_U0_ap_start;
wire    write_result_U0_ap_done;
wire    write_result_U0_ap_continue;
wire    write_result_U0_ap_idle;
wire    write_result_U0_ap_ready;
wire    write_result_U0_m_axi_gmem0_AWVALID;
wire   [63:0] write_result_U0_m_axi_gmem0_AWADDR;
wire   [0:0] write_result_U0_m_axi_gmem0_AWID;
wire   [31:0] write_result_U0_m_axi_gmem0_AWLEN;
wire   [2:0] write_result_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] write_result_U0_m_axi_gmem0_AWBURST;
wire   [1:0] write_result_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] write_result_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] write_result_U0_m_axi_gmem0_AWPROT;
wire   [3:0] write_result_U0_m_axi_gmem0_AWQOS;
wire   [3:0] write_result_U0_m_axi_gmem0_AWREGION;
wire   [0:0] write_result_U0_m_axi_gmem0_AWUSER;
wire    write_result_U0_m_axi_gmem0_WVALID;
wire   [31:0] write_result_U0_m_axi_gmem0_WDATA;
wire   [3:0] write_result_U0_m_axi_gmem0_WSTRB;
wire    write_result_U0_m_axi_gmem0_WLAST;
wire   [0:0] write_result_U0_m_axi_gmem0_WID;
wire   [0:0] write_result_U0_m_axi_gmem0_WUSER;
wire    write_result_U0_m_axi_gmem0_ARVALID;
wire   [63:0] write_result_U0_m_axi_gmem0_ARADDR;
wire   [0:0] write_result_U0_m_axi_gmem0_ARID;
wire   [31:0] write_result_U0_m_axi_gmem0_ARLEN;
wire   [2:0] write_result_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] write_result_U0_m_axi_gmem0_ARBURST;
wire   [1:0] write_result_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] write_result_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] write_result_U0_m_axi_gmem0_ARPROT;
wire   [3:0] write_result_U0_m_axi_gmem0_ARQOS;
wire   [3:0] write_result_U0_m_axi_gmem0_ARREGION;
wire   [0:0] write_result_U0_m_axi_gmem0_ARUSER;
wire    write_result_U0_m_axi_gmem0_RREADY;
wire    write_result_U0_m_axi_gmem0_BREADY;
wire    write_result_U0_out_r_read;
wire    write_result_U0_size_read;
wire    write_result_U0_outStream_read;
wire    write_result_U0_ap_ext_blocking_n;
wire    write_result_U0_ap_str_blocking_n;
wire    write_result_U0_ap_int_blocking_n;
wire    out_r_c_full_n;
wire   [63:0] out_r_c_dout;
wire   [2:0] out_r_c_num_data_valid;
wire   [2:0] out_r_c_fifo_cap;
wire    out_r_c_empty_n;
wire    size_c1_full_n;
wire   [31:0] size_c1_dout;
wire   [2:0] size_c1_num_data_valid;
wire   [2:0] size_c1_fifo_cap;
wire    size_c1_empty_n;
wire    inStream1_full_n;
wire   [31:0] inStream1_dout;
wire   [2:0] inStream1_num_data_valid;
wire   [2:0] inStream1_fifo_cap;
wire    inStream1_empty_n;
wire    inStream2_full_n;
wire   [31:0] inStream2_dout;
wire   [2:0] inStream2_num_data_valid;
wire   [2:0] inStream2_fifo_cap;
wire    inStream2_empty_n;
wire    size_c_full_n;
wire   [31:0] size_c_dout;
wire   [2:0] size_c_num_data_valid;
wire   [2:0] size_c_fifo_cap;
wire    size_c_empty_n;
wire    outStream_full_n;
wire   [31:0] outStream_dout;
wire   [2:0] outStream_num_data_valid;
wire   [2:0] outStream_fifo_cap;
wire    outStream_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_read_input_U0_ap_ready;
wire    ap_sync_read_input_U0_ap_ready;
reg    ap_sync_reg_read_input_1_U0_ap_ready;
wire    ap_sync_read_input_1_U0_ap_ready;
wire   [0:0] start_for_write_result_U0_din;
wire    start_for_write_result_U0_full_n;
wire   [0:0] start_for_write_result_U0_dout;
wire    start_for_write_result_U0_empty_n;
wire   [0:0] start_for_compute_add_U0_din;
wire    start_for_compute_add_U0_full_n;
wire   [0:0] start_for_compute_add_U0_dout;
wire    start_for_compute_add_U0_empty_n;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;
wire    ap_ext_blocking_n;
wire    ap_str_blocking_n;
wire    ap_int_blocking_n;
reg    ap_ext_blocking_n_reg;
reg    ap_str_blocking_n_reg;
reg    ap_int_blocking_n_reg;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_input_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_input_1_U0_ap_ready = 1'b0;
end

vadd_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in1(in1),
    .in2(in2),
    .out_r(out_r),
    .size(size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .event_start(event_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

vadd_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read_input_U0_m_axi_gmem0_ARVALID),
    .I_CH0_ARREADY(gmem0_ARREADY),
    .I_CH0_ARADDR(read_input_U0_m_axi_gmem0_ARADDR),
    .I_CH0_ARLEN(read_input_U0_m_axi_gmem0_ARLEN),
    .I_CH0_RVALID(gmem0_RVALID),
    .I_CH0_RREADY(read_input_U0_m_axi_gmem0_RREADY),
    .I_CH0_RDATA(gmem0_RDATA),
    .I_CH0_RFIFONUM(gmem0_RFIFONUM),
    .I_CH0_AWVALID(write_result_U0_m_axi_gmem0_AWVALID),
    .I_CH0_AWREADY(gmem0_AWREADY),
    .I_CH0_AWADDR(write_result_U0_m_axi_gmem0_AWADDR),
    .I_CH0_AWLEN(write_result_U0_m_axi_gmem0_AWLEN),
    .I_CH0_WVALID(write_result_U0_m_axi_gmem0_WVALID),
    .I_CH0_WREADY(gmem0_WREADY),
    .I_CH0_WDATA(write_result_U0_m_axi_gmem0_WDATA),
    .I_CH0_WSTRB(write_result_U0_m_axi_gmem0_WSTRB),
    .I_CH0_BVALID(gmem0_BVALID),
    .I_CH0_BREADY(write_result_U0_m_axi_gmem0_BREADY)
);

vadd_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read_input_1_U0_m_axi_gmem1_ARVALID),
    .I_CH0_ARREADY(gmem1_ARREADY),
    .I_CH0_ARADDR(read_input_1_U0_m_axi_gmem1_ARADDR),
    .I_CH0_ARLEN(read_input_1_U0_m_axi_gmem1_ARLEN),
    .I_CH0_RVALID(gmem1_RVALID),
    .I_CH0_RREADY(read_input_1_U0_m_axi_gmem1_RREADY),
    .I_CH0_RDATA(gmem1_RDATA),
    .I_CH0_RFIFONUM(gmem1_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(gmem1_BVALID),
    .I_CH0_BREADY(1'b0)
);

vadd_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_write_result_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .out_r(out_r),
    .out_r_c_din(entry_proc_U0_out_r_c_din),
    .out_r_c_num_data_valid(out_r_c_num_data_valid),
    .out_r_c_fifo_cap(out_r_c_fifo_cap),
    .out_r_c_full_n(out_r_c_full_n),
    .out_r_c_write(entry_proc_U0_out_r_c_write),
    .ap_ext_blocking_n(entry_proc_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(entry_proc_U0_ap_str_blocking_n),
    .ap_int_blocking_n(entry_proc_U0_ap_int_blocking_n)
);

vadd_read_input read_input_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input_U0_ap_start),
    .start_full_n(start_for_compute_add_U0_full_n),
    .ap_done(read_input_U0_ap_done),
    .ap_continue(read_input_U0_ap_continue),
    .ap_idle(read_input_U0_ap_idle),
    .ap_ready(read_input_U0_ap_ready),
    .start_out(read_input_U0_start_out),
    .start_write(read_input_U0_start_write),
    .m_axi_gmem0_AWVALID(read_input_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(read_input_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(read_input_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(read_input_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(read_input_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(read_input_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(read_input_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(read_input_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(read_input_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(read_input_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(read_input_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(read_input_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(read_input_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(read_input_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(read_input_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(read_input_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(read_input_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(read_input_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(read_input_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(read_input_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(read_input_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(read_input_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(read_input_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(read_input_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(read_input_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(read_input_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(read_input_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(read_input_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(read_input_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(read_input_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(read_input_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(read_input_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .in_r(in1),
    .size(size),
    .size_c1_din(read_input_U0_size_c1_din),
    .size_c1_num_data_valid(size_c1_num_data_valid),
    .size_c1_fifo_cap(size_c1_fifo_cap),
    .size_c1_full_n(size_c1_full_n),
    .size_c1_write(read_input_U0_size_c1_write),
    .inStream1_din(read_input_U0_inStream1_din),
    .inStream1_num_data_valid(inStream1_num_data_valid),
    .inStream1_fifo_cap(inStream1_fifo_cap),
    .inStream1_full_n(inStream1_full_n),
    .inStream1_write(read_input_U0_inStream1_write),
    .ap_ext_blocking_n(read_input_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(read_input_U0_ap_str_blocking_n),
    .ap_int_blocking_n(read_input_U0_ap_int_blocking_n)
);

vadd_read_input_1 read_input_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input_1_U0_ap_start),
    .ap_done(read_input_1_U0_ap_done),
    .ap_continue(read_input_1_U0_ap_continue),
    .ap_idle(read_input_1_U0_ap_idle),
    .ap_ready(read_input_1_U0_ap_ready),
    .m_axi_gmem1_AWVALID(read_input_1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(read_input_1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(read_input_1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(read_input_1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(read_input_1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(read_input_1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(read_input_1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(read_input_1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(read_input_1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(read_input_1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(read_input_1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(read_input_1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(read_input_1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(read_input_1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(read_input_1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(read_input_1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(read_input_1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(read_input_1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(read_input_1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(read_input_1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(read_input_1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(read_input_1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(read_input_1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(read_input_1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(read_input_1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(read_input_1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(read_input_1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(read_input_1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(read_input_1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(read_input_1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(read_input_1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(read_input_1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .inStream2_din(read_input_1_U0_inStream2_din),
    .inStream2_num_data_valid(inStream2_num_data_valid),
    .inStream2_fifo_cap(inStream2_fifo_cap),
    .inStream2_full_n(inStream2_full_n),
    .inStream2_write(read_input_1_U0_inStream2_write),
    .in_r(in2),
    .size(size),
    .ap_ext_blocking_n(read_input_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(read_input_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(read_input_1_U0_ap_int_blocking_n)
);

vadd_compute_add compute_add_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_add_U0_ap_start),
    .ap_done(compute_add_U0_ap_done),
    .ap_continue(compute_add_U0_ap_continue),
    .ap_idle(compute_add_U0_ap_idle),
    .ap_ready(compute_add_U0_ap_ready),
    .size_dout(size_c1_dout),
    .size_num_data_valid(size_c1_num_data_valid),
    .size_fifo_cap(size_c1_fifo_cap),
    .size_empty_n(size_c1_empty_n),
    .size_read(compute_add_U0_size_read),
    .size_c_din(compute_add_U0_size_c_din),
    .size_c_num_data_valid(size_c_num_data_valid),
    .size_c_fifo_cap(size_c_fifo_cap),
    .size_c_full_n(size_c_full_n),
    .size_c_write(compute_add_U0_size_c_write),
    .inStream1_dout(inStream1_dout),
    .inStream1_num_data_valid(inStream1_num_data_valid),
    .inStream1_fifo_cap(inStream1_fifo_cap),
    .inStream1_empty_n(inStream1_empty_n),
    .inStream1_read(compute_add_U0_inStream1_read),
    .inStream2_dout(inStream2_dout),
    .inStream2_num_data_valid(inStream2_num_data_valid),
    .inStream2_fifo_cap(inStream2_fifo_cap),
    .inStream2_empty_n(inStream2_empty_n),
    .inStream2_read(compute_add_U0_inStream2_read),
    .outStream_din(compute_add_U0_outStream_din),
    .outStream_num_data_valid(outStream_num_data_valid),
    .outStream_fifo_cap(outStream_fifo_cap),
    .outStream_full_n(outStream_full_n),
    .outStream_write(compute_add_U0_outStream_write),
    .ap_ext_blocking_n(compute_add_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(compute_add_U0_ap_str_blocking_n),
    .ap_int_blocking_n(compute_add_U0_ap_int_blocking_n)
);

vadd_write_result write_result_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_result_U0_ap_start),
    .ap_done(write_result_U0_ap_done),
    .ap_continue(write_result_U0_ap_continue),
    .ap_idle(write_result_U0_ap_idle),
    .ap_ready(write_result_U0_ap_ready),
    .m_axi_gmem0_AWVALID(write_result_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(gmem0_AWREADY),
    .m_axi_gmem0_AWADDR(write_result_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(write_result_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(write_result_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(write_result_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(write_result_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(write_result_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(write_result_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(write_result_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(write_result_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(write_result_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(write_result_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(write_result_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(gmem0_WREADY),
    .m_axi_gmem0_WDATA(write_result_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(write_result_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(write_result_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(write_result_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(write_result_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(write_result_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(1'b0),
    .m_axi_gmem0_ARADDR(write_result_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(write_result_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(write_result_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(write_result_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(write_result_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(write_result_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(write_result_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(write_result_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(write_result_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(write_result_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(write_result_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(1'b0),
    .m_axi_gmem0_RREADY(write_result_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(32'd0),
    .m_axi_gmem0_RLAST(1'b0),
    .m_axi_gmem0_RID(1'd0),
    .m_axi_gmem0_RFIFONUM(9'd0),
    .m_axi_gmem0_RUSER(1'd0),
    .m_axi_gmem0_RRESP(2'd0),
    .m_axi_gmem0_BVALID(gmem0_BVALID),
    .m_axi_gmem0_BREADY(write_result_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(gmem0_BRESP),
    .m_axi_gmem0_BID(gmem0_BID),
    .m_axi_gmem0_BUSER(gmem0_BUSER),
    .out_r_dout(out_r_c_dout),
    .out_r_num_data_valid(out_r_c_num_data_valid),
    .out_r_fifo_cap(out_r_c_fifo_cap),
    .out_r_empty_n(out_r_c_empty_n),
    .out_r_read(write_result_U0_out_r_read),
    .size_dout(size_c_dout),
    .size_num_data_valid(size_c_num_data_valid),
    .size_fifo_cap(size_c_fifo_cap),
    .size_empty_n(size_c_empty_n),
    .size_read(write_result_U0_size_read),
    .outStream_dout(outStream_dout),
    .outStream_num_data_valid(outStream_num_data_valid),
    .outStream_fifo_cap(outStream_fifo_cap),
    .outStream_empty_n(outStream_empty_n),
    .outStream_read(write_result_U0_outStream_read),
    .ap_ext_blocking_n(write_result_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(write_result_U0_ap_str_blocking_n),
    .ap_int_blocking_n(write_result_U0_ap_int_blocking_n)
);

vadd_fifo_w64_d4_S out_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_out_r_c_din),
    .if_full_n(out_r_c_full_n),
    .if_write(entry_proc_U0_out_r_c_write),
    .if_dout(out_r_c_dout),
    .if_num_data_valid(out_r_c_num_data_valid),
    .if_fifo_cap(out_r_c_fifo_cap),
    .if_empty_n(out_r_c_empty_n),
    .if_read(write_result_U0_out_r_read)
);

vadd_fifo_w32_d2_S size_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_size_c1_din),
    .if_full_n(size_c1_full_n),
    .if_write(read_input_U0_size_c1_write),
    .if_dout(size_c1_dout),
    .if_num_data_valid(size_c1_num_data_valid),
    .if_fifo_cap(size_c1_fifo_cap),
    .if_empty_n(size_c1_empty_n),
    .if_read(compute_add_U0_size_read)
);

vadd_fifo_w32_d2_S inStream1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_inStream1_din),
    .if_full_n(inStream1_full_n),
    .if_write(read_input_U0_inStream1_write),
    .if_dout(inStream1_dout),
    .if_num_data_valid(inStream1_num_data_valid),
    .if_fifo_cap(inStream1_fifo_cap),
    .if_empty_n(inStream1_empty_n),
    .if_read(compute_add_U0_inStream1_read)
);

vadd_fifo_w32_d2_S inStream2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_1_U0_inStream2_din),
    .if_full_n(inStream2_full_n),
    .if_write(read_input_1_U0_inStream2_write),
    .if_dout(inStream2_dout),
    .if_num_data_valid(inStream2_num_data_valid),
    .if_fifo_cap(inStream2_fifo_cap),
    .if_empty_n(inStream2_empty_n),
    .if_read(compute_add_U0_inStream2_read)
);

vadd_fifo_w32_d2_S size_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_add_U0_size_c_din),
    .if_full_n(size_c_full_n),
    .if_write(compute_add_U0_size_c_write),
    .if_dout(size_c_dout),
    .if_num_data_valid(size_c_num_data_valid),
    .if_fifo_cap(size_c_fifo_cap),
    .if_empty_n(size_c_empty_n),
    .if_read(write_result_U0_size_read)
);

vadd_fifo_w32_d2_S outStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_add_U0_outStream_din),
    .if_full_n(outStream_full_n),
    .if_write(compute_add_U0_outStream_write),
    .if_dout(outStream_dout),
    .if_num_data_valid(outStream_num_data_valid),
    .if_fifo_cap(outStream_fifo_cap),
    .if_empty_n(outStream_empty_n),
    .if_read(write_result_U0_outStream_read)
);

vadd_start_for_write_result_U0 start_for_write_result_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_result_U0_din),
    .if_full_n(start_for_write_result_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_write_result_U0_dout),
    .if_empty_n(start_for_write_result_U0_empty_n),
    .if_read(write_result_U0_ap_ready)
);

vadd_start_for_compute_add_U0 start_for_compute_add_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_add_U0_din),
    .if_full_n(start_for_compute_add_U0_full_n),
    .if_write(read_input_U0_start_write),
    .if_dout(start_for_compute_add_U0_dout),
    .if_empty_n(start_for_compute_add_U0_empty_n),
    .if_read(compute_add_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_input_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_input_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_input_1_U0_ap_ready <= ap_sync_read_input_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_input_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_input_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_input_U0_ap_ready <= ap_sync_read_input_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_ext_blocking_n_reg <= ap_ext_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_int_blocking_n_reg <= ap_int_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    ap_str_blocking_n_reg <= ap_str_blocking_n;
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b0) & (ap_ext_blocking_n == 1'b1))) begin
        stall_done_ext = 1'b1;
    end else begin
        stall_done_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b0) & (ap_int_blocking_n == 1'b1))) begin
        stall_done_int = 1'b1;
    end else begin
        stall_done_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b0) & (ap_str_blocking_n == 1'b1))) begin
        stall_done_str = 1'b1;
    end else begin
        stall_done_str = 1'b0;
    end
end

always @ (*) begin
    if (((ap_ext_blocking_n_reg == 1'b1) & (ap_ext_blocking_n == 1'b0))) begin
        stall_start_ext = 1'b1;
    end else begin
        stall_start_ext = 1'b0;
    end
end

always @ (*) begin
    if (((ap_int_blocking_n_reg == 1'b1) & (ap_int_blocking_n == 1'b0))) begin
        stall_start_int = 1'b1;
    end else begin
        stall_start_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_str_blocking_n_reg == 1'b1) & (ap_str_blocking_n == 1'b0))) begin
        stall_start_str = 1'b1;
    end else begin
        stall_start_str = 1'b0;
    end
end

assign ap_done = write_result_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (write_result_U0_ap_ext_blocking_n & read_input_U0_ap_ext_blocking_n & read_input_1_U0_ap_ext_blocking_n & entry_proc_U0_ap_ext_blocking_n & compute_add_U0_ap_ext_blocking_n);

assign ap_idle = (write_result_U0_ap_idle & read_input_U0_ap_idle & read_input_1_U0_ap_idle & entry_proc_U0_ap_idle & compute_add_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (write_result_U0_ap_int_blocking_n & read_input_U0_ap_int_blocking_n & read_input_1_U0_ap_int_blocking_n & entry_proc_U0_ap_int_blocking_n & compute_add_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (write_result_U0_ap_str_blocking_n & read_input_U0_ap_str_blocking_n & read_input_1_U0_ap_str_blocking_n & entry_proc_U0_ap_str_blocking_n & compute_add_U0_ap_str_blocking_n);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_read_input_1_U0_ap_ready = (read_input_1_U0_ap_ready | ap_sync_reg_read_input_1_U0_ap_ready);

assign ap_sync_read_input_U0_ap_ready = (read_input_U0_ap_ready | ap_sync_reg_read_input_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_input_U0_ap_ready & ap_sync_read_input_1_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign compute_add_U0_ap_continue = 1'b1;

assign compute_add_U0_ap_start = start_for_compute_add_U0_empty_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign event_done = ap_done;

assign gmem0_BID = 1'd0;

assign gmem0_BRESP = 2'd0;

assign gmem0_BUSER = 1'd0;

assign gmem0_RID = 1'd0;

assign gmem0_RLAST = 1'b0;

assign gmem0_RRESP = 2'd0;

assign gmem0_RUSER = 1'd0;

assign gmem1_RID = 1'd0;

assign gmem1_RLAST = 1'b0;

assign gmem1_RRESP = 2'd0;

assign gmem1_RUSER = 1'd0;

assign read_input_1_U0_ap_continue = 1'b1;

assign read_input_1_U0_ap_start = ((ap_sync_reg_read_input_1_U0_ap_ready ^ 1'b1) & ap_start);

assign read_input_U0_ap_continue = 1'b1;

assign read_input_U0_ap_start = ((ap_sync_reg_read_input_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_compute_add_U0_din = 1'b1;

assign start_for_write_result_U0_din = 1'b1;

assign write_result_U0_ap_continue = ap_continue;

assign write_result_U0_ap_start = start_for_write_result_U0_empty_n;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "vadd_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //vadd

